[package]
name = "guessing_game"
version = "0.1.0"
authors = ["matinjun <44500594+matinjun@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.1"
